### ISSUE TITLE
是否有本课程的学习群?

### ISSUE THREAD

**Issue by TerryLiu** [impact-eintr/LinuxC#3]
感谢大佬创建了本项目. 
希望能搞个本课程或C语言的vx群, 方便大家沟通学习.
若大佬没有建群计划, 大家加我后,我来拉群也可以. 我的vx号是数字的:幺呜呜零琪琪四五六
加友时备注: linuxC加群
期待大佬的回复

**Comment by impact-eintr** [comment]
谢谢你的issues，群链接在README中，欢迎交流
